baseURL = 'https://example.org/'
languageCode = 'zh-CN'
title = '自学新世界'
theme = 'relearn'
defaultContentLanguage = 'zh'

[params]
  themeVariant = 'tima-dark'
  math = true
  collapsibleMenu = true

[params.utteranc]
  enable = true
  repo = "abdulle-sabaf/erudeon"
  issueTerm = "pathname"
  theme = "github-dark"


[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]
